---
- hosts: localhost
  connection: local
  become: false
  gather_facts: true
  vars:
    vms_data:
      - { name: "app1", security_groups: ["apps"]}
      - { name: "app2", security_groups: ["apps"]}
      - { name: "database", security_groups: ["db"]}
      - { name: "frontend", security_groups: ["frontend"]}
  tasks:
    - name: Including role
      include_role:
        name: osp-servers
      loop: "{{ vms_data }}"
      loop_control:
        loop_var: vm
