---
- hosts: localhost
  connection: local
  become: false
  gather_facts: true
  vars:
    vms_data:
      - { name: "app1", security_groups: ["apps"]}
      - { name: "app2", security_groups: ["apps"]}
      - { name: "database", security_groups: ["db"]}
      - { name: "frontend", security_groups: ["frontend"]}
  roles:
    - role: osp-servers
      vars:
        vm: "{{ item }}"
      loop: "{{ vms_data }}"
